spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    hikari:
      poolName: minio
      auto-commit: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update



  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

server:
  port: ${SERVER_PORT}

logging:
  level:
    ROOT: info
    uz.retail: info

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
  show-actuator: false
  api-docs:
    enabled: true
    path: "/v2/api-docs"
    version: openapi_3_0

minio:
  url: ${MINIO_URL}
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}